branch-defaults:
  INT-SKY-GRADD:
    environment: missioncontrol-stg1
    group_suffix: null
  master:
    environment: missioncontrol-prod
    group_suffix: null
environment-defaults:
  missioncontrol-stg:
    branch: null
    repository: null
global:
  application_name: missioncontrol
  branch: null
  default_ec2_keyname: missioncontrol-key
  default_platform: Docker 17.09.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
